services:
  # 1. База даних
  db:
    image: mysql:8.0
    # Завжди задаємо ім'я контейнера, щоб легше було звертатися
    container_name: spellbook-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306" # Доступ до БД з вашого комп'ютера
    volumes:
      - db_data:/var/lib/mysql # Зберігаємо дані, щоб не зникали
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spellbook-network

  # 2. Бекенд (API)
  api:
    build: ./server
    container_name: spellbook-api
    restart: always
    env_file:
      - .env
    environment:
      # Магія Docker: хост БД тепер називається просто 'db' (як назва сервісу вище)
      - DB_HOST=db 
    depends_on:
      - db
    networks:
      - spellbook-network

  # 3. Фронтенд
  frontend:
    build: .
    container_name: spellbook-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Це змусить Nginx бачити ваш файл
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    networks:
      - spellbook-network

  certbot:
      image: certbot/certbot
      volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot


# Створюємо спільну мережу
networks:
  spellbook-network:
    driver: bridge

# Створюємо місце для зберігання даних БД
volumes:
  db_data:
